# Generated by Django 5.0.6 on 2024-06-03 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cunsol_app', '0003_users_delete_user'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='users',
            table='users',
        ),
    ]
